### ISSUE TITLE
关于代码中叶子节点分数的疑问

### ISSUE THREAD

**Issue by HandleCoding** [Ulti-Dreisteine/local-interpretation-for-gbdt#1]
你好，你的代码中实现的叶子节点分数也就是children_score是用的样本的正类占比，而论文中描述正类占比是前作论文随机森林解释模型中的方法，对于gbdt作者采用的是$T_j(x_i)$来当做叶子节点的分数

**Comment by HandleCoding** [comment]
我有一个疑问，单颗树训练完成后，叶子节点的分数做为一个回归树应该是确定的，但是应该怎么获取这些叶子节点的分数呢

**Comment by Ulti-Dreisteine** [comment]
好的，谢谢提醒，我这两天看看再给你回复哈

**Comment by Ulti-Dreisteine** [comment]
> 我有一个疑问，单颗树训练完成后，叶子节点的分数做为一个回归树应该是确定的，但是应该怎么获取这些叶子节点的分数呢



> 我有一个疑问，单颗树训练完成后，叶子节点的分数做为一个回归树应该是确定的，但是应该怎么获取这些叶子节点的分数呢

**Comment by Ulti-Dreisteine** [comment]
> 我有一个疑问，单颗树训练完成后，叶子节点的分数做为一个回归树应该是确定的，但是应该怎么获取这些叶子节点的分数呢

在原论文里关于对GBDT的node score/leaf score计算并没有看到很清晰的表述, 只说明了如何从child node score反推上一层的parent node score. 这里的node score需要具体查看GBDT算法里的定义, 目前代码里先暂时用RF的方式替代，更新的代码里补充了一些注释.

**Comment by HandleCoding** [comment]
感谢您的回复：
1.注意到图1上方这段所述，On the right hand side of Fig 1, all the **node average scores** and feature contributions on the tree are marked. 
2.在Algorithm 3 的算法框图中有score =所有树之和的内容。
3.在第四节第一段中，Nevertheless, the problem of this version is that the average of labels on a leaf node is not always equal to the score on it. So the valuable model information in **these scores are not utilized** and the method is not appropriate for different GBDT versions。说明了利用样本标签分布的问题，然后再次提到了这个分数。

综上，由于gbdt里面的单颗树采用的是回归树，文中提到了分数是节点平均分数（上述1），推测这里指代的分数应该为叶子节点中所有梯度残差的平均。

个人拙见。
